import Image from "next/image"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { CustomCursor } from "@/components/advanced-cursor"
import { Enhanced3DBackground } from "@/components/enhanced-3d-background"
import { ClientsSection } from "@/components/clients-section"
import { NewsletterSignup } from "@/components/newsletter-signup"
import { Navigation } from "@/components/ui/navigation"
import { EditableText } from "@/components/editable-text"
import { EditableImage } from "@/components/editable-image"